language: go

env: GO111MODULE=on GOFLAGS='-mod vendor'

go:
  - 1.13.3

before_script:
  - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.21.0

script:
  - make build
  - golangci-lint run
  - go test -v -race ./...