dist: bionic

language: go

env: GO111MODULE=on GOFLAGS='-mod vendor'

go:
  - 1.13.x


before_script:
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - make build
  - golangci-lint run
  - go test -v -race ./...