language: go

env: GO111MODULE=on GOFLAGS='-mod vendor'

go:
  - 1.3.3
  - 1.4.2
  - 1.5.1
  - release
  - tip

before_script:
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - make build
  - golangci-lint run
  - go test -v -race ./...