services:
  homing-pigeon:
    volumes:
    - shared_socket:/tmp
    - ./:/go/src/github.com/softonic/homing-pigeon
    build:
      context: .
      dockerfile: Dockerfile
    image: softonic/homing-pigeon:dev
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
      ELASTICSEARCH_FLUSH_MAX_SIZE: "250"
      ELASTICSEARCH_FLUSH_MAX_INTERVAL_MS: "5000"
      RABBITMQ_URL: "amqp://guest:guest@rabbit-mq:5672"
      RABBITMQ_DLX_NAME: "dead-letters"
      RABBITMQ_DLX_QUEUE_NAME: "dead-letters"
      RABBITMQ_EXCHANGE_NAME: "homing-pigeon"
      RABBITMQ_EXCHANGE_TYPE: "fanout"
      RABBITMQ_QUEUE_NAME: "messages"
      RABBITMQ_QUEUE_BINDING_KEY: "#"
      RABBITMQ_QOS_PREFETCH_COUNT: "1000"
      MESSAGE_BUFFER_LENGTH: "1000"
      ACK_BUFFER_LENGTH: "500"
      GRPC_GO_LOG_VERBOSITY_LEVEL: 99
      GRPC_GO_LOG_SEVERITY_LEVEL: info
      REQUEST_MIDDLEWARES_SOCKET: "passthrough:///unix:///tmp/hprq"
      RESPONSE_MIDDLEWARES_SOCKET: "passthrough:///unix:///tmp/hprp"
      READ_ADAPTER: "AMQP"
      WRITE_ADAPTER: "ELASTIC"
    depends_on:
      rabbit-mq:
        condition: service_healthy
  request-middleware-pass:
    platform: linux/amd64
    volumes:
      - shared_socket:/tmp
    image: softonic/hp-pass-middleware:0.1.0
    environment:
      IN_SOCKET: "/tmp/hprq"
    command: ["-stderrthreshold=INFO"]
  reponse-middleware-pass:
    platform: linux/amd64
    volumes:
      - shared_socket:/tmp
    image: softonic/hp-pass-middleware:0.1.0
    environment:
      IN_SOCKET: "/tmp/hprp"
    command: ["-stderrthreshold=INFO"]
  rabbit-mq:
    image: rabbitmq:3.8-management
    ports:
      - 15672:15672
      - 5672:5672
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 20s
      retries: 5
  elasticsearch:
    platform: linux/amd64
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.4.2
    ports:
      - 9200:9200
    environment:
      - node.name=elasticsearch
      - cluster.name=pigeon
      - bootstrap.memory_lock=true
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - bootstrap.system_call_filter=false
    ulimits:
      memlock:
        soft: -1
        hard: -1

volumes:
  shared_socket:
    driver: local
