version: '3.7'

services:
  homing-pigeon:
    build:
      context: .
      dockerfile: Dockerfile
    image: softonic/homing-pigeon:dev
  rabbit-mq:
    image: rabbitmq:3.8-management
    ports:
      - 15672:15672
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.4.2
    environment:
      - node.name=elasticsearch
      - cluster.name=pigeon
      - bootstrap.memory_lock=true
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1