services:
  homing-pigeon:
    volumes:
      - shared_socket:/tmp
      - ./:/go/src/github.com/softonic/homing-pigeon
    build:
      context: .
      dockerfile: Dockerfile
    image: softonic/homing-pigeon:dev
    user: root
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
      ELASTICSEARCH_FLUSH_MAX_SIZE: "250"
      ELASTICSEARCH_FLUSH_MAX_INTERVAL_MS: "5000"
      RABBITMQ_URL: "amqp://guest:guest@rabbit-mq:5672"
      RABBITMQ_DLX_NAME: "dead-letters"
      RABBITMQ_DLX_QUEUE_NAME: "dead-letters"
      RABBITMQ_EXCHANGE_NAME: "homing-pigeon"
      RABBITMQ_EXCHANGE_TYPE: "fanout"
      RABBITMQ_QUEUE_NAME: incoming-local-{{ .ConsumerId }}
      RABBITMQ_QUEUE_BINDING_KEY: "#"
      RABBITMQ_QOS_PREFETCH_COUNT: "1000"
      RABBITMQ_QUEUE_MAX_PRIORITY: "2"
      MESSAGE_BUFFER_LENGTH: "1000"
      ACK_BUFFER_LENGTH: "500"
      GRPC_GO_LOG_VERBOSITY_LEVEL: 99
      GRPC_GO_LOG_SEVERITY_LEVEL: info
      REQUEST_MIDDLEWARES_SOCKET: "passthrough:///unix:///tmp/req1"
      RESPONSE_MIDDLEWARES_SOCKET: "passthrough:///unix:///tmp/res1"
      MIDDLEWARE_BATCH_SIZE: 10
      MIDDLEWARE_BATCH_TIMEOUT_MS: 1000
      READ_ADAPTER: "AMQP"
      WRITE_ADAPTER: "ELASTIC"
    command: ["-stderrthreshold=INFO"]
    depends_on:
      rabbit-mq:
        condition: service_healthy
  request-middleware-pass:
    volumes:
      - shared_socket:/tmp
    image: softonic/hp-pass-middleware:dev
    user: root
    environment:
      IN_SOCKET: "/tmp/req1"
    command: ["-stderrthreshold=INFO"]
  response-middleware-pass:
    volumes:
      - shared_socket:/tmp
    image: softonic/hp-pass-middleware:dev
    user: root
    environment:
      IN_SOCKET: "/tmp/res1"
      OUT_SOCKET: "passthrough:///unix:///tmp/res2"
    command: ["-stderrthreshold=INFO"]
  response-middleware-pass-2:
    volumes:
      - shared_socket:/tmp
    image: softonic/hp-pass-middleware:dev
    user: root
    environment:
      IN_SOCKET: "/tmp/res2"
    command: ["-stderrthreshold=INFO"]
  rabbit-mq:
    image: rabbitmq:3.8-management
    ports:
      - 15672:15672
      - 5672:5672
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 20s
      retries: 5
  elasticsearch:
    #platform: linux/arm64
    image: docker.elastic.co/elasticsearch/elasticsearch:9.1.0
    ports:
      - 9200:9200
    environment:
      - node.name=elasticsearch
      - cluster.name=pigeon
      - bootstrap.memory_lock=true
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g -Des.failure_store_feature_flag_enabled=true"
      - "_JAVA_OPTS=-XX:UseSVE=0"
    ulimits:
      memlock:
        soft: -1
        hard: -1

volumes:
  shared_socket:
    driver: local
