// Code generated by protoc-gen-go. DO NOT EDIT.
// source: middleware.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Data is represented with an unique ID and the body that contains the actual data.
type Data struct {
	Messages             []*Data_Message `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_10e8b4c446957f50, []int{0}
}

func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetMessages() []*Data_Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

type Data_Message struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Body                 []byte   `protobuf:"bytes,2,opt,name=Body,proto3" json:"Body,omitempty"`
	Acked                bool     `protobuf:"varint,3,opt,name=acked,proto3" json:"acked,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Data_Message) Reset()         { *m = Data_Message{} }
func (m *Data_Message) String() string { return proto.CompactTextString(m) }
func (*Data_Message) ProtoMessage()    {}
func (*Data_Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_10e8b4c446957f50, []int{0, 0}
}

func (m *Data_Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data_Message.Unmarshal(m, b)
}
func (m *Data_Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data_Message.Marshal(b, m, deterministic)
}
func (m *Data_Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data_Message.Merge(m, src)
}
func (m *Data_Message) XXX_Size() int {
	return xxx_messageInfo_Data_Message.Size(m)
}
func (m *Data_Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Data_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Data_Message proto.InternalMessageInfo

func (m *Data_Message) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Data_Message) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Data_Message) GetAcked() bool {
	if m != nil {
		return m.Acked
	}
	return false
}

func init() {
	proto.RegisterType((*Data)(nil), "proto.Data")
	proto.RegisterType((*Data_Message)(nil), "proto.Data.Message")
}

func init() { proto.RegisterFile("middleware.proto", fileDescriptor_10e8b4c446957f50) }

var fileDescriptor_10e8b4c446957f50 = []byte{
	// 211 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xc8, 0xcd, 0x4c, 0x49,
	0xc9, 0x49, 0x2d, 0x4f, 0x2c, 0x4a, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53,
	0x4a, 0x35, 0x5c, 0x2c, 0x2e, 0x89, 0x25, 0x89, 0x42, 0xfa, 0x5c, 0x1c, 0xb9, 0xa9, 0xc5, 0xc5,
	0x89, 0xe9, 0xa9, 0xc5, 0x12, 0x8c, 0x0a, 0xcc, 0x1a, 0xdc, 0x46, 0xc2, 0x10, 0x85, 0x7a, 0x20,
	0x69, 0x3d, 0x5f, 0x88, 0x5c, 0x10, 0x5c, 0x91, 0x94, 0x33, 0x17, 0x3b, 0x54, 0x50, 0x88, 0x8f,
	0x8b, 0xc9, 0x33, 0x45, 0x82, 0x51, 0x81, 0x51, 0x83, 0x25, 0x88, 0xc9, 0x33, 0x45, 0x48, 0x88,
	0x8b, 0xc5, 0x29, 0x3f, 0xa5, 0x52, 0x82, 0x49, 0x81, 0x51, 0x83, 0x27, 0x08, 0xcc, 0x16, 0x12,
	0xe1, 0x62, 0x4d, 0x4c, 0xce, 0x4e, 0x4d, 0x91, 0x60, 0x56, 0x60, 0xd4, 0xe0, 0x08, 0x82, 0x70,
	0x8c, 0x8c, 0xb8, 0xb8, 0x7c, 0xe1, 0x0e, 0x13, 0x52, 0xe1, 0x62, 0xf3, 0x48, 0xcc, 0x4b, 0xc9,
	0x49, 0x15, 0xe2, 0x46, 0xb2, 0x5b, 0x0a, 0x99, 0xa3, 0xc4, 0xe0, 0x64, 0xc2, 0xa5, 0x92, 0x9c,
	0x9f, 0xab, 0x57, 0x9c, 0x9f, 0x56, 0x92, 0x9f, 0x97, 0x99, 0xac, 0x97, 0x91, 0x9f, 0x9b, 0x99,
	0x97, 0x5e, 0x90, 0x99, 0x9e, 0x9a, 0x9f, 0xa7, 0x87, 0xf0, 0xa6, 0x13, 0x92, 0xc9, 0x01, 0x8c,
	0x49, 0x6c, 0x60, 0x33, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x3e, 0x52, 0x25, 0x63, 0x09,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MiddlewareClient is the client API for Middleware service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MiddlewareClient interface {
	// Handle the given data and return it.
	Handle(ctx context.Context, in *Data, opts ...grpc.CallOption) (*Data, error)
}

type middlewareClient struct {
	cc *grpc.ClientConn
}

func NewMiddlewareClient(cc *grpc.ClientConn) MiddlewareClient {
	return &middlewareClient{cc}
}

func (c *middlewareClient) Handle(ctx context.Context, in *Data, opts ...grpc.CallOption) (*Data, error) {
	out := new(Data)
	err := c.cc.Invoke(ctx, "/proto.Middleware/Handle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MiddlewareServer is the server API for Middleware service.
type MiddlewareServer interface {
	// Handle the given data and return it.
	Handle(context.Context, *Data) (*Data, error)
}

// UnimplementedMiddlewareServer can be embedded to have forward compatible implementations.
type UnimplementedMiddlewareServer struct {
}

func (*UnimplementedMiddlewareServer) Handle(ctx context.Context, req *Data) (*Data, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Handle not implemented")
}

func RegisterMiddlewareServer(s *grpc.Server, srv MiddlewareServer) {
	s.RegisterService(&_Middleware_serviceDesc, srv)
}

func _Middleware_Handle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Data)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiddlewareServer).Handle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Middleware/Handle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiddlewareServer).Handle(ctx, req.(*Data))
	}
	return interceptor(ctx, in, info, handler)
}

var _Middleware_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Middleware",
	HandlerType: (*MiddlewareServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Handle",
			Handler:    _Middleware_Handle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "middleware.proto",
}
